# Generated by Django 3.1.5 on 2021-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permut_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
