language: python
python:
  - '3.7'

before_script:
  - coverage erase

env: DJANGO_SETTINGS_MODULE="maieuclic_project.settings.test_settings"

services:
  - postgresql

script:
  - coverage run maieuclic_project/manage.py test tests --settings=maieuclic_project.settings.test_settings

# safelist
branches:
  only:
    - staging
