# Generated by Django 3.1.5 on 2021-02-17 08:10

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permut_creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permut',
            fields=[
                ('permut_id', models.AutoField(primary_key=True, serialize=False)),
                ('permut_state', models.CharField(choices=[('CR', 'created'), ('NO', 'notified'), ('BD', 'being discussed'), ('UN', 'under negociation'), ('RE', 'rejected')], default='CR', max_length=2)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermutAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leaving_this_place', to=settings.AUTH_USER_MODEL)),
                ('email_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_searching_this_place', to=settings.AUTH_USER_MODEL)),
                ('permut_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permut_management.permut')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permut_creation.place')),
            ],
        ),
    ]
